### ISSUE TITLE
Build pipeline seems to be broken, new releases are not published

### ISSUE THREAD

**Issue by jablan** [phrase/phrase-java#16]
https://github.com/phrase/phrase-java/actions/runs/17317297713/job/49162541061

**Comment by bikmazefe** [comment]
Fixed https://github.com/phrase/phrase-java/actions/runs/17725138095/job/50364250567

**Comment by jablan** [comment]
@bikmazefe you can give it a try: https://github.com/phrase/openapi/pull/904

**Comment by jablan** [comment]
@maximAtanasov that part is still broken, needs to be fixed. of course, we accept external PRs too 😉
